language: node_js

node_js:
  - 'node'

sudo: required

services:
  - docker

script:
  - yarn test --coverage
  - yarn build

after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
