import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { FunctionComponent, PropsWithChildren } from 'react'

const roboto = Roboto({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FunctionComponent<PropsWithChildren<{}>> =
  ({ children }) => (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )

export default RootLayout
